### ISSUE TITLE
S2110 Measurements are 0

### ISSUE THREAD

**Issue by xemlo** [Seeed-Studio/Seeed_Arduino_S2110#1]
If your power settings on the 2110 are set to Interval Power vs. Always On, the data measurements are always 0.  If you connect a USB-C cable to the sensor, then the data comes out correctly.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
